/// Aviation abbreviations constants used in weather reports and advisories
class AviationAbbreviations {
  static const Map<String, String> abbreviations = {
    'AAF': 'Army Air Field',
    'AAL': 'Above aerodrome level',
    'AATM': 'At all times',
    'ABD': 'Aboard',
    'ABNDT': 'Abundant',
    'ABNML': 'Abnormal',
    'ABT': 'About',
    'ABV': 'Above',
    'ACARS': 'Aircraft communication addressing & reporting system',
    'ACCUM': 'Accumulate',
    'ACFT': 'Aircraft',
    'ACK': 'Acknowledge',
    'ACL': 'Altimeter check location',
    'ACLD': 'Above clouds',
    'ACLT': 'Accelerate',
    'ACPT': 'Accept',
    'ACR': 'Air carrier',
    'ACRBT': 'Acrobatic',
    'ACRS': 'Across',
    'ACSL': 'Standing lenticular altocumulus',
    'ACT': 'Active or activated or activity',
    'ACTG': 'Acting',
    'ACTV': 'Active',
    'ACTVT': 'Activate',
    'ACYC': 'Anticyclonic',
    'ADA': 'Advisory area',
    'ADDN': 'Addition',
    'ADF': 'Automatic direction finder',
    'ADIZ': 'Air defense identification zone',
    'ADJ': 'Adjacent',
    'ADQT': 'Adequate',
    'ADRNDCK': 'Adirondack',
    'ADV': 'Advise',
    'ADVCTN': 'Advection',
    'ADVN': 'Advance',
    'ADVY': 'Advisory',
    'ADVZY': 'Advisory',
    'AFB': 'Air Force Base',
    'AFCT': 'Affect',
    'AFD': 'Airport/Facility Directory',
    'AFDK': 'After dark',
    'AFSS': 'Automated Flight Service Station',
    'AFT': 'After',
    'AFTN': 'Afternoon',
    'AGL': 'Above ground level',
    'AHD': 'Ahead',
    'AIM': 'Aeronautical Information Manual',
    'AIRMET': 'Airmen\'s Meteorological Information',
    'ALF': 'Aloft',
    'ALG': 'Along',
    'ALGHNY': 'Allegheny',
    'ALNMT': 'Alignment',
    'ALQDS': 'All quadrants',
    'ALS': 'Approach light system',
    'ALSEC': 'All sectors',
    'ALSF-1': 'Standard 2400\' high-intensity approach lighting system with sequenced flashers (Category I configuration)',
    'ALSF-2': 'Standard 2400\' high-intensity approach lighting system with sequenced flashers (Category II configuration)',
    'ALSTG': 'Altimeter setting',
    'ALT': 'Altitude',
    'ALTA': 'Alberta',
    'ALTM': 'Altimeter',
    'ALTN': 'Alternate',
    'ALUTN': 'Aleutian',
    'AM': 'Ante meridiem',
    'AMS': 'Air mass',
    'AMSL': 'Above mean sea level',
    'ANCPT': 'Anticipate',
    'ANLYS': 'Analysis',
    'AO1': 'ASOS automated observation without precipitation discriminator (rain/snow)',
    'AO2': 'ASOS automated observation with precipitation discriminator (rain/snow)',
    'AOA': 'At or above',
    'AOB': 'At or below',
    'AOE': 'Airport of entry',
    'APCH': 'Approach',
    'APL': 'Airport lights',
    'APLCN': 'Appalachian',
    'APN': 'Apron',
    'APRNT': 'Apparent',
    'APROP': 'Appropriate',
    'APRX': 'Approximate',
    'ARB': 'Air Reserve Base',
    'ARFOR': 'Area forecast',
    'ARINC': 'Aeronautical Radio, Incorporated',
    'ARND': 'Around',
    'ARTC': 'Air route traffic control',
    'ARTCC': 'Air Route Traffic Control Center',
    'ASAP': 'As soon as possible',
    'ASDA': 'Accelerate-stop distance available',
    'ASL': 'Above sea level',
    'ASOS': 'Automated surface observing system',
    'ASPH': 'Asphalt',
    'ATA': 'Actual time of arrival',
    'ATIS': 'Automatic terminal information service',
    'ATLC': 'Atlantic',
    'AURBO': 'Aurora Borealis',
    'AUTH': 'Authorized',
    'AUTO': 'Automatic',
    'AVG': 'Average',
    'AVGAS': 'Aviation gasoline',
    'AWOS': 'Automatic weather observing/reporting system',
    'AWY': 'Airway',
    'AZM': 'Azimuth',
    'BACLIN': 'Baroclinic',
    'BAJA': 'Baja California',
    'BATROP': 'Barotropic',
    'BC': 'British Columbia',
    'BCH': 'Beach',
    'BCKG': 'Backing',
    'BCM': 'Become',
    'BCMG': 'Becoming',
    'BCMS': 'Becomes',
    'BD': 'Blowing dust',
    'BDA': 'Bermuda',
    'BDRY': 'Boundary',
    'BFDK': 'Before dark',
    'BFR': 'Before',
    'BGN': 'Begin',
    'BGNG': 'Beginning',
    'BGNS': 'Begins',
    'BHND': 'Behind',
    'BINOVC': 'Breaks in overcast',
    'BKN': 'Broken',
    'BLD': 'Build',
    'BLDG': 'Building',
    'BLDS': 'Builds',
    'BLDUP': 'Buildup',
    'BLKHLS': 'Black Hills',
    'BLKT': 'Blanket',
    'BLKTG': 'Blanketing',
    'BLKTS': 'Blankets',
    'BLO': 'Below',
    'BLZD': 'Blizzard',
    'BN': 'Blowing sand',
    'BND': 'Bound',
    'BNDRY': 'Boundary',
    'BNDRYS': 'Boundaries',
    'BNTH': 'Beneath',
    'BOOTHEEL': 'Bootheel',
    'BR': 'Branch',
    'BRG': 'Branching',
    'BRS': 'Branches',
    'BRF': 'Brief',
    'BRK': 'Break',
    'BRKG': 'Breaking',
    'BRKHIC': 'Breaks in higher clouds',
    'BRKS': 'Breaks',
    'BRKSHR': 'Berkshire',
    'BRKSHRS': 'Berkshires',
    'BRM': 'Barometer',
    'BS': 'Blowing snow',
    'BTWN': 'Between',
    'BYD': 'Beyond',
    // ...continuing with hundreds more abbreviations...

    // T-TX Aviation Weather Symbols
    'T': 'Thunder',
    'TCNTL': 'Transcontinental',
    'TDA': 'Today',
    'TEMP': 'Temperature',
    'THD': 'Thunderhead',
    'THDR': 'Thunder',
    'THK': 'Thick',
    'THKNG': 'Thickening',
    'THKNS': 'Thickness',
    'THKR': 'Thicker',
    'THKST': 'Thickest',
    'THN': 'Thin',
    'THNG': 'Thinning',
    'THNR': 'Thinner',
    'THNST': 'Thinnest',
    'THR': 'Threshold',
    'THRFTR': 'Thereafter',
    'THRU': 'Through',
    'THRUT': 'Throughout',
    'THSD': 'Thousand',
    'THTN': 'Threaten',
    'THTND': 'Threatened',
    'THTNG': 'Threatening',
    'THTNS': 'Threatens',
    'TIL': 'Until',
    'TMPRY': 'Temporary',
    'TMPRYLY': 'Temporarilly',
    'TMW': 'Tomorrow',
    'TN': 'Tennessee',
    'TNDCY': 'Tendency',
    'TNDCYS': 'Tendencies',
    'TNGT': 'Tonight',
    'TNTV': 'Tentative',
    'TNTVLY': 'Tentatively',
    'TOPS': 'Tops',
    'TOVC': 'Top of overcast',
    'TPG': 'Topping',
    'TRBL': 'Trouble',
    'TRIB': 'Tributary',
    'TRKG': 'Tracking',
    'TRML': 'Terminal',
    'TRMT': 'Terminate',
    'TRMTD': 'Terminated',
    'TRMTG': 'Terminating',
    'TRMTS': 'Terminates',
    'TRNSP': 'Transport',
    'TRNSPG': 'Transporting',
    'TROF': 'Trough',
    'TROFS': 'Troughs',
    'TROP': 'Tropopause',
    'TRPCD': 'Tropical continental',
    'TRPCL': 'Tropical',
    'TRRN': 'Terrain',
    'TRSN': 'Transition',
    'TRW': 'Thunderstorm',
    'TRW+': 'Thunderstorm with heavy rain shower',
    'TSFR': 'Transfer',
    'TSFRD': 'Transfered',
    'TSFRG': 'Transfering',
    'TSFRS': 'Transfers',
    'TSHWR': 'Thundershower',
    'TSHWRS': 'Thundershowers',
    'TSNT': 'Transient',
    'TSQLS': 'Thundersqualls',
    'TSTM': 'Thunderstorm',
    'TSTMS': 'Thunderstorms',
    'TSW': 'Thunderstorm with snow showers',
    'TSW+': 'Thunderstorm with heavy snow showers',
    'TURBC': 'Turbulence',
    'TURBT': 'Turbulent',
    'TWD': 'Toward',
    'TWDS': 'Towards',
    'TWI': 'Twilight',
    'TWRG': 'Towering',
    'TX': 'Texas',

    // Additional common aviation abbreviations
    'PIREP': 'Pilot weather report',
    'PIREPS': 'Pilot weather reports',
    'SIGMET': 'Significant meteorological information',
    'METAR': 'Aviation routine weather report',
    'TAF': 'Terminal aerodrome forecast',
    'SPECI': 'Special weather report',
    'WX': 'Weather',
    'VFR': 'Visual flight rules',
    'IFR': 'Instrument flight rules',
    'MVFR': 'Marginal visual flight rules',
    'LIFR': 'Low instrument flight rules',
  };
}
