/// Special weather conditions constants for METAR/TAF interpretation
class SpecialConditions {
  static const Map<String, String> conditions = {
    'NOSIG': 'No significant change',
    'TEMPO': 'Temporary',
    'BECMG': 'Becoming',
    'PROB': 'Probability',
    'FM': 'From',
    'TL': 'Until',
    'AT': 'At',
    'WS': 'Wind shear',
    'RMK': 'Remarks',
    'AUTO': 'Automated observation',
    'COR': 'Correction',
    'AMD': 'Amendment',
    'NIL': 'No report',
    'SPECI': 'Special observation',
    'METAR': 'Aviation routine weather report',
    'TAF': 'Terminal aerodrome forecast',
    'CAVOK': 'Ceiling and visibility OK',
    'NSW': 'No significant weather',
    'SHRA': 'Rain showers',
    'SHSN': 'Snow showers',
    'TSGR': 'Thunderstorm with hail',
    'TSRA': 'Thunderstorm with rain',
    'FZRA': 'Freezing rain',
    'FZDZ': 'Freezing drizzle',
    'BLSN': 'Blowing snow',
    'BLDU': 'Blowing dust',
    'BLSA': 'Blowing sand',
    'DRDU': 'Drifting dust',
    'DRSA': 'Drifting sand',
    'MIFG': 'Shallow fog',
    'PRFG': 'Partial fog',
    'BCFG': 'Patches of fog',
    'VCFG': 'Fog in vicinity',
    'VCSH': 'Showers in vicinity',
    'VCTS': 'Thunderstorm in vicinity',
    'VCBLDU': 'Blowing dust in vicinity',
    'VCBLSA': 'Blowing sand in vicinity',
    'VCBLSN': 'Blowing snow in vicinity',
    'VCDS': 'Duststorm in vicinity',
    'VCSS': 'Sandstorm in vicinity',
    'VCPO': 'Dust devils in vicinity',
    'VCFC': 'Funnel cloud in vicinity',
  };
}
