// T-TX Aviation Weather Symbols to be added to weather_interpretation_service.dart
// Add these to the _aviationAbbreviations map after 'SYS': 'System',

const Map<String, String> tTxSymbols = {
  'T': 'Thunder',
  'TCNTL': 'Transcontinental',
  // Note: 'TCU': 'Towering cumulus' already exists in _cloudTypes
  'TDA': 'Today',
  'TEMP': 'Temperature',
  'THD': 'Thunderhead',
  'THDR': 'Thunder',
  'THK': 'Thick',
  'THKNG': 'Thickening',
  'THKNS': 'Thickness',
  'THKR': 'Thicker',
  'THKST': 'Thickest',
  'THN': 'Thin',
  'THNG': 'Thinning',
  'THNR': 'Thinner',
  'THNST': 'Thinnest',
  'THR': 'Threshold',
  'THRFTR': 'Thereafter',
  'THRU': 'Through',
  'THRUT': 'Throughout',
  'THSD': 'Thousand',
  'THTN': 'Threaten',
  'THTND': 'Threatened',
  'THTNG': 'Threatening',
  'THTNS': 'Threatens',
  'TIL': 'Until',
  'TMPRY': 'Temporary',
  'TMPRYLY': 'Temporarilly',
  'TMW': 'Tomorrow',
  'TN': 'Tennessee',
  'TNDCY': 'Tendency',
  'TNDCYS': 'Tendencies',
  'TNGT': 'Tonight',
  'TNTV': 'Tentative',
  'TNTVLY': 'Tentatively',
  'TOPS': 'Tops',
  'TOVC': 'Top of overcast',
  'TPG': 'Topping',
  'TRBL': 'Trouble',
  'TRIB': 'Tributary',
  'TRKG': 'Tracking',
  'TRML': 'Terminal',
  'TRMT': 'Terminate',
  'TRMTD': 'Terminated',
  'TRMTG': 'Terminating',
  'TRMTS': 'Terminates',
  'TRNSP': 'Transport',
  'TRNSPG': 'Transporting',
  'TROF': 'Trough',
  'TROFS': 'Troughs',
  'TROP': 'Tropopause',
  'TRPCD': 'Tropical continental',
  'TRPCL': 'Tropical',
  'TRRN': 'Terrain',
  'TRSN': 'Transition',
  'TRW': 'Thunderstorm',
  'TRW+': 'Thunderstorm with heavy rain shower',
  'TSFR': 'Transfer',
  'TSFRD': 'Transfered',
  'TSFRG': 'Transfering',
  'TSFRS': 'Transfers',
  'TSHWR': 'Thundershower',
  'TSHWRS': 'Thundershowers',
  'TSNT': 'Transient',
  'TSQLS': 'Thundersqualls',
  'TSTM': 'Thunderstorm',
  'TSTMS': 'Thunderstorms',
  // Note: 'TS': 'Thunderstorm' already exists in _descriptors, but we need these additional variants:
  'TS': 'Thunderstorm with snow',
  'TS+': 'Thunderstorm with heavy snow',
  'TSW': 'Thunderstorm with snow showers',
  'TSW+': 'Thunderstorm with heavy snow showers',
  'TURBC': 'Turbulence',
  'TURBT': 'Turbulent',
  'TWD': 'Toward',
  'TWDS': 'Towards',
  'TWI': 'Twilight',
  'TWRG': 'Towering',
  'TX': 'Texas',
};
