/// Aviation abbreviations constants (U-Z) used in weather reports and advisories
class UVWXYZAbbreviations {
  static const Map<String, String> abbreviations = {
    // U
    'UDDF': 'Up and down drafts',
    'UN': 'Unable',
    'UNAVBL': 'Unavailable',
    'UNEC': 'Unnecessary',
    'UNKN': 'Unknown',
    'UNL': 'Unlimited',
    'UNRELBL': 'Unreliable',
    'UNRSTD': 'Unrestricted',
    'UNSATFY': 'Unsatisfactory',
    'UNSBL': 'Unseasonable',
    'UNSTBL': 'Unstable',
    'UNSTDY': 'Unsteady',
    'UNSTL': 'Unsettle',
    'UNSTLD': 'Unsettled',
    'UNUSBL': 'Unusable',
    'UPDFTS': 'Updrafts',
    'UPR': 'Upper',
    'UPSLP': 'Upslope',
    'UPSTRM': 'Upstream',
    'URG': 'Urgent',
    'USBL': 'Usable',
    'UT': 'Utah',
    'UVV': 'Upward vertical velocity',
    'UVVS': 'Upward vertical velocities',
    'UWNDS': 'Upper winds',

    // V
    'VA': 'Virginia',
    'VARN': 'Variation',
    'VCNTY': 'Vicinity',
    'VCOT': 'VFR conditions on top',
    'VCTR': 'Vector',
    'VDUC': 'VAS Data Utilization Center (NSSFC)',
    'VFY': 'Verify',
    'VFYD': 'Verified',
    'VFYG': 'Verifying',
    'VFYS': 'Verifies',
    'VLCTY': 'Velocity',
    'VLCTYS': 'Velocities',
    'VLNT': 'Violent',
    'VLNTLY': 'Violently',
    'VLY': 'Valley',
    'VLYS': 'Valleys',
    'VMC': 'Visual meteorological conditions',
    'VOL': 'Volume',
    'VORT': 'Vorticity',
    'VR': 'Veer',
    'VRG': 'Veering',
    'VRBL': 'Variable',
    'VRISL': 'Vancouver Island, BC',
    'VRS': 'Veers',
    'VRT MOTN': 'Vertical Motion',
    'VRY': 'Very',
    'VSB': 'Visible',
    'VSBY': 'Visibility',
    'VSBYDR': 'Visibility decreasing rapidly',
    'VSBYIR': 'Visibility increasing rapidly',
    'VT': 'Vermont',
    'VV': 'Vertical velocity',

    // W
    'W': 'West',
    'WA': 'Washington',
    'WAA': 'Warm Air Advection',
    'WBND': 'West bound',
    'WDLY': 'Widely',
    'WDSPRD': 'Widespread',
    'WEA': 'Weather',
    'WFO': 'Weather Forecast Office',
    'WFOS': 'Weather Forecast Offices',
    'WFP': 'Warm front passage',
    'WI': 'Wisconsin',
    'WIBIS': 'Will be issued',
    'WINT': 'Winter',
    'WK': 'Weak',
    'WKDAY': 'Weekday',
    'WKEND': 'Weekend',
    'WKNG': 'Weakening',
    'WKNS': 'Weakens',
    'WKR': 'Weaker',
    'WKST': 'Weakest',
    'WKN': 'Weaken',
    'WL': 'Will',
    'WLY': 'Westerly',
    'WND': 'Wind',
    'WNDS': 'Winds',
    'WNW': 'West-northwest',
    'WNWLY': 'West-northwesterly',
    'WNWRN': 'West-northwestern',
    'WNWWD': 'West-northwestward',
    'WO': 'Without',
    'WPLTO': 'Western Plateau',
    'WRM': 'Warm',
    'WRMG': 'Warming',
    'WRN': 'Western',
    'WRMR': 'Warmer',
    'WRMST': 'Warmest',
    'WRMFNT': 'Warm front',
    'WRMFNTL': 'Warm Frontal',
    'WRNG': 'Warning',
    'WRNGS': 'Warnings',
    'WRS': 'Worse',
    'WSHFT': 'Wind shift',
    'WSHFTS': 'Wind Shifts',
    'WSFO': 'Weather Service Forecast Office',
    'WSFOS': 'Weather Service Forecast Offices',
    'WSO': 'Weather Service Office',
    'WSOS': 'Weather Service Offices',
    'WSTCH': 'Wasatch Range',
    'WSW': 'West-southwest',
    'WSWLY': 'West-southwesterly',
    'WSWRN': 'West-southwestern',
    'WSWWD': 'West-southwestward',
    'WTR': 'Water',
    'WTRS': 'Waters',
    'WTSPT': 'Waterspout',
    'WTSPTS': 'Waterspouts',
    'WUD': 'Would',
    'WV': 'West Virginia',
    'WVS': 'Waves',
    'WW': 'Severe Weather Watch',
    'WWAMKC': 'Status Report',
    'WWD': 'Westward',
    'WWS': 'Severe Weather Watches',
    'WX': 'Weather',
    'WY': 'Wyoming',

    // X
    'XCP': 'Except',
    'XPC': 'Expect',
    'XPCD': 'Expected',
    'XPCG': 'Expecting',
    'XPCS': 'Expects',
    'XPLOS': 'Explosive',
    'XTND': 'Extend',
    'XTNDD': 'Extended',
    'XTNDG': 'Extending',
    'XTRM': 'Extreme',
    'XTRMLY': 'Extremely',

    // Y
    'YDA': 'Yesterday',
    'YKN': 'Yukon',
    'YLSTN': 'Yellowstone',

    // Z
    'ZL': 'Freezing drizzle',
    'ZN': 'Zone',
    'ZNS': 'Zones',
    'ZR': 'Freezing rain',
  };
}
