default_platform(:ios)

platform :ios do
  desc "Push a new release build to App Store Connect"
  lane :release do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      force: true,
      precheck_include_in_app_purchases: false
    )
  end
end
EOF < /dev/null